### ISSUE TITLE
Doesn't launch the game - black screen

### ISSUE THREAD

**Issue by kkon10** [p1xel8ted/GYK-QModManagerReloaded#1]
**If the bug report is about QMod Manager Reloaded, a screenshot of the "Checklist" page must be attached. Any without will be ignored.**

**Please include a screenshot of QMod Manager Reloaded so that I can see what mods you have installed and their load order.**

**What mod/tool are you reporting a bug for?**
- Mod/tool - **Qmod manager reloaded** 
- Version - **1.0.8193.37173 (07/06/2022 20:39:06)**

**Describe the bug**
- A clear and concise description of what the bug is - **Launching the GOG game from the QMR doesn't work - stuck on black screen**

**To Reproduce**
Detailed steps to reproduce the behavior:
**Launch the GOG game directly from the tool**

**Desktop (please complete the following information):**
- Windows version - **Windows 10**
- Windows language - **English**
- Game language  - **English**
- Game platform - **Gog**

**Additional context**
- Add any other context about the problem here.

**Comment by p1xel8ted** [comment]
Please try https://github.com/p1xel8ted/GYK-QModManagerReloaded/releases/tag/v1.0.8199.39666

I tested with a fresh GOG installed, and QMod install, and all appeared good.

**Comment by kkon10** [comment]
That was really fast! It works now. Thanks a lot!
