### ISSUE TITLE
[BUG] Infinite Game Loading Screen

### ISSUE THREAD

**Issue by GangstaPichu** [p1xel8ted/GYK-QModManagerReloaded#10]
**Check List**
![Capture](https://user-images.githubusercontent.com/88961592/209752799-4df3188c-ec8f-4da8-b05b-9753ffef056e.PNG)

**Required Logs**

Please delete both logs and test the game again so it generates fresh logs with only relevant entries.
[Player.log](https://github.com/p1xel8ted/GYK-QModManagerReloaded/files/10311936/Player.log)

[qmod_reloaded_log.txt](https://github.com/p1xel8ted/GYK-QModManagerReloaded/files/10312017/qmod_reloaded_log.txt)

**What version are you reporting a bug for?**
Version: v1.0.8272.35378 (Latest)

**Describe the bug**
Before this the game worked fine. I was using the launcher and was using 3 mods (2 of them were made for the older qmod, but still seem to function despite the launcher saying otherwise). The more further I got the more I noticed it would be nice for certain mods. I went back added a few or so more for thing I thought would be nice. Installed them and now I can't play. I even disabled them and left the ones that I knew did work now don't work. The game gets stuck on the loading gui screen when popping into the game. The only thing I did differently cause the game bugged up when switching something and I had to verify my files is that I accidentally clicked "Remove Intros" button. I didn't click that before and the mods were fine that I was using. 

(As a side note: I have played without the mods and it works fine in vanilla without the launcher)
**To Reproduce**
Not sure, but maybe something with clicking remove intros button. 

That or verifying files on steam does something to it. 

**Expected behavior**
Being able to pop in without the gui loading screen getting stuck. 

**Screenshots/Video**
https://medal.tv/games/graveyard-keeper/clips/O1hDEadlQvVky/d13376xYOGWm?invite=cr-MSxRclQsMzM5MTA2NDEs

**Desktop (please complete the following information):**
- Windows 10
- Windows language
- Game language 

- Steam

**Additional context**
- Add any other context about the problem here.

**Comment by p1xel8ted** [comment]
Update Beam Me Up Gerry
