### ISSUE TITLE
[BUG] Gerry Vanishing from Morgue and Tavern basement

### ISSUE THREAD

**Issue by CLittleLunaC** [p1xel8ted/GYK-QModManagerReloaded#11]
**Requirements**
- A screenshot of the "Checklist" page must be attached. Any without will be ignored.

**Required Logs**
Please delete both logs and test the game again, so it generates fresh logs with only relevant entries.
[Player.log](https://github.com/p1xel8ted/GYK-QModManagerReloaded/files/10442961/Player.log)
[qmod_reloaded_log.txt](https://github.com/p1xel8ted/GYK-QModManagerReloaded/files/10442962/qmod_reloaded_log.txt)

**What version are you reporting a bug for?**
- Version 1.0.8411.17421

**Describe the bug**
Gerry is missing from the game, and I even tried to "spawn" him by triggering the Town cutscene. I started a new save to play through the game with mods. He was there in the beginning but soon vanished. I removed my mods to see if it was one of my mods, and he was still missing with just Qmod reloaded

**To Reproduce**
Detailed steps to reproduce the behavior:
1. Enable patch
2. Enter save
3. Go to the morgue
4. See the error

**Expected behavior**
To not be Soft locked by Gerry being missing
**Screenshots/Video**
![Untitled2](https://user-images.githubusercontent.com/41792970/213102394-afeea298-a1b2-4915-a233-86f47c9865ad.jpg)
![Untitled3](https://user-images.githubusercontent.com/41792970/213102403-06dd4dc4-bc67-4d5c-8187-7f66f5204956.jpg)
![Untitled](https://user-images.githubusercontent.com/41792970/213103358-d8a8463c-e265-452a-a350-c0a0113585f6.jpg)

**Desktop (please complete the following information):**
- Windows 10
- English
- English
- Steam

**Additional context**

**Comment by p1xel8ted** [comment]
Get the Gerry Fixer from the Gerry's Junk Trunk files section. And ensure the other mods that contain Gerry are all updated to prevent the issue happening again. Some cutscenes require manual intervention which I'm working on a more robust solution that doesn't require me to fix it manually.
